### ISSUE TITLE
Missing metrics about the RTR clients

### ISSUE THREAD

**Issue by netixx** [NLnetLabs/rtrtr#102]
Hello,

I would like to get metrics about the RTR clients that are connected to a given instance.

For example:
- the number of clients currently connected
- the last time a VRP was sent to the client (by client IP, VRP afi)
- the count of VRP sent to each client (by client IP, VRP afi)

These are just ideas (depending on what is implemented, some are redundant) :) 

Currently I only see metrics related to the upstream part, but none related to the downstream part.

**Comment by partim** [comment]
Thank you for the suggestion! This seems like a very useful addition, indeed.

**Comment by netixx** [comment]
If you need someone to test a branch or test release, I am available.
Sorry I cannot help on the code, I don't know rust... yet :)

**Comment by partim** [comment]
I just realised that #115 doesn’t include metrics of the current serial number of the unit or the number of VRPs, which we should probably add. So I’ll re-open the issue.
