### ISSUE TITLE
Support for setting PDU refresh, retry and expire parameters

### ISSUE THREAD

**Issue by netixx** [NLnetLabs/rtrtr#105]
Since version 1 of the RTR protocol, the server can send info about the refresh, retry and expire parameters: https://datatracker.ietf.org/doc/html/rfc8210#section-6

It would be nice if rtrtr allows those parameters to be send and configured via target config options.

For additional reference, stayrtr allows those parameters to be set via the command line: https://github.com/bgp/stayrtr/blob/febec67d0d5e30e8314ff12cfca7b03acf96f771/cmd/stayrtr/stayrtr.go#L57

**Comment by partim** [comment]
Thank you for the suggestion. I really should have included those initially.

**Comment by netixx** [comment]
thanks!
