### ISSUE TITLE
no logs on stderr with rtrtr v0.3.0

### ISSUE THREAD

**Issue by DonOtuseGH** [NLnetLabs/rtrtr#120]
Hi there,

we used rtrtr v0.2.2 on Alpine Linux 3.18.3 container image for a couple of months without any problem and would like to upgrade to the latest version 0.3.0.

It builds and runs with Alpine 3.18.6, 3.19.1 and 3.20.0 without any issue but we don't see logs anymore.

Version 0.2.2 produces logs like this:

```
HTTP server listening on 0.0.0.0:8323
Target http: link status: healthy
Unit json: successfully updated.
Target rtr: Got update (553895 entries)
Target http: Got update (553895 entries)
Target http: link status: healthy
RTR: Got reset query.
RTR: Got reset query.
Unit json: update without changes.
RTR: Got reset query.
```

Version 0.3.0 shows nothing.

Log config in rtrtr.conf configuration file has not been changed and is set as follows:

```
log_level = "debug"
log_target = "stderr"
```

Please can you have a look and identify, whats wrong here?

Thanks and best regards, Don.

**Comment by partim** [comment]
Thank you for the report!

It looks like command line handling resets the log level to “warn” if no log level-related options are given. Fix incoming.

I’ll start the release process for RTRTR 0.3.1 as well.
