### ISSUE TITLE
rtrtr does not accept rpki-client formatted json

### ISSUE THREAD

**Issue by ties** [NLnetLabs/rtrtr#20]
When investigating https://github.com/bgp/stayrtr/issues/13 I discovered that rtrtr is intollerant of rpki-client's output.

When I set up rtrtr to load data from _both_ routinator and rpki-client (the config used is attached), I get the following error
```
docker run -p 8080:8080 -p 9001:9001 -v `pwd`/rtrtr.conf:/etc/rtrtr.conf nlnetlabs/rtrtr -c /etc/rtrtr.conf
Unit alias-rpki-client: Updating from http://[host]:8888/objects/validated
Unit alias-routinator: Updating from http://[host]:9556/json
Target http-json: link status: healthy
Unit alias-rtr: Connecting ...
Unit alias-rtr: Failed to connect to RTR server [host]:3323: Connection refused (os error 111)
Unit alias-rtr: Connection failed. Awaiting reconnect.
alias-rpki-client: Failed reading source: invalid type: integer `3215`, expected a string with an AS number at line 29 column 16
```

Please consider supporting both formats for interoperability.

### Configuration:
[rtrtr_example.txt](https://github.com/NLnetLabs/rtrtr/files/6846845/rtrtr_example.txt)

**Comment by partim** [comment]
This has been fixed as part of #30.
