### ISSUE TITLE
support rpki-client 7.x JSON output

### ISSUE THREAD

**Issue by reschke** [NLnetLabs/rtrtr#36]
Current versions of rpki-client unfortunately serialize ASNs as numbers, not strings. RTRTR is unhappy about that (rightfully, IMHO):

~~~
rtrtr::units::json local: Failed reading source: invalid value: string "45753", expected a string with an AS number at line 10384 column 20
~~~

(I opened this as ticket here for visibility; if the maintainers think rpki-client needs to reverse that change, that's fine as well and we should then talk to those developers)

**Comment by partim** [comment]
This was fixed while refactoring how payload data is kept in #30. The next version will happily read rpki-client data – and will generally be more generous about what appears in the JSON.

**Comment by reschke** [comment]
Ack. Sorry for the duplicate issue (I only looked at the open ones).

**Comment by partim** [comment]
No worries. It’s kind of cool to be able to say ‘Oh, yeah, I just fixed that.’ ;)
