### ISSUE TITLE
Pkg workflow lacks test from published

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/rtrtr#71]
Packaging workflows for other NLnet Labs products test that upgrade from a previously published package works as expected.

This wasn't yet added for RTRTR because initially there were no published packages to test upgrade from.

However, it should now be added to be consistent with and to have the additional sanity check like we do for other products.

**Comment by partim** [comment]
Am I correct in assuming that the changes made for #90 solve this issue?

**Comment by ximon18** [comment]
> Am I correct in assuming that the changes made for #90 solve this issue?

Yes.
