### ISSUE TITLE
log SLURM file processing

### ISSUE THREAD

**Issue by DonOtuseGH** [NLnetLabs/rtrtr#84]
Hello,

In the process of evaluating different PRKI software solutions, we are currently preparing `Routinator` and `RTRTR` for the planned deployment.
We are using RTRTR version `0.2.2` and a `SLURM` JSON file to filter and append ROAs for our use case. This basically works, but it would be nice if there could be an additional log entry for the successful processing.

GoRTR generates e.g. the following output:

`Slurm filtering: 390083 kept, 2 removed, 1 asserted`

Maybe a similar message could be added to RTRTR?

Please find below a working configuration example, the logs and the validation command below:

**rtrtr.conf**

```
log_level = "debug"
log_target = "stderr"
http-listen = ["0.0.0.0:8323"]
[units.json]
type = "json"
uri = "https://console.rpki-client.org/vrps.json"
refresh = 60
[units.slurm]
type = "slurm"
source = "json"
files = [ "/home/rtrtr/slurm.json" ]
[targets.rtr]
type = "rtr"
listen = [ "0.0.0.0:3323" ]
unit = "slurm"
[targets.http]
type = "http"
path = "/json"
format = "json"
unit = "slurm"
```

**slurm.json**

```json
{
  "slurmVersion": 1,
  "validationOutputFilters": {
    "prefixFilters": [],
    "bgpsecFilters": []
  },
  "locallyAddedAssertions": {
    "prefixAssertions": [
      {
        "asn": 64546,
        "prefix": "192.168.255.0/24",
        "maxPrefixLength": 24,
        "comment": "RTR Health Check"
      }
    ],
    "bgpsecAssertions": []
  }
}
```

**logs**

```
HTTP server listening on 0.0.0.0:8323
Target http: link status: healthy
Unit json: successfully updated.
Target http: Got update (395400 entries)
Target http: link status: healthy
Target rtr: Got update (395400 entries)
```

**validation command**

```sh
$ rtrclient -e -t csv -o /dev/stdout tcp 127.0.0.1 3323 2>/dev/null | grep '^192.168'
192.168.255.0, 24, 24, 64546
```

Thank you in advance for your consideration of this topic!

Best regards, Don.

**Comment by partim** [comment]
Sorry for the late response!

We’ll add a log message as you suggested in the next release.

**Comment by sumkincpp** [comment]
This would be really useful.

Another point - if slurm file does not exist, applying slurm is simply skipped with no errors shown in the log.
