### ISSUE TITLE
No packages for Debian Bookworm on packages.nlnetlabs.nl

### ISSUE THREAD

**Issue by 991jo** [NLnetLabs/rtrtr#92]
The NLNet Labs Software Package Repository currently does not provide packages for Debian Bullseye.

Would it be possible to add them?

**Comment by AlexanderBand** [comment]
We recenly updated https://nlnetlabs.nl/packages/ to clarify this. 

```
As a general guideline, we offer packages for new operating systems in the following version of our products. This may take several weeks or months, depending on our release schedule. 
```

We haven't done an RTRTR release in a while so that's why there's no bookworm package yet. We'll do one soon though!
